<?php
$data = array (
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '民宿.度假',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '19',
    'name' => '民宿.度假',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '钱江源',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => '钱江源',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '药王山',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => '药王山',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '小湖南',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => '小湖南',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '九龙湖',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => '九龙湖',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '廿八都',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '41',
    'name' => '廿八都',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '欢乐送',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '20',
    'name' => '欢乐送',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '鲜花',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '鲜花',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '蛋糕',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => '蛋糕',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '下午茶',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '24',
    'name' => '下午茶',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '其它',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '其它',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '安利',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '27',
    'name' => '安利',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '雅姿 美容化妆品',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 2,
    'id' => '36',
    'name' => '雅姿 美容化妆品',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '恒时凝颜系列',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '39',
    'name' => '恒时凝颜系列',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '美白系列',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '37',
    'name' => '美白系列',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '卓效美肌系列',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '38',
    'name' => '卓效美肌系列',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '五星商家',
    'measure_unit' => '间',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => '8',
    'level' => 0,
    'id' => '18',
    'name' => '五星商家',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '日本料理',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '日本料理',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '韩国菜',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '韩国菜',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '自助餐',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => '自助餐',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '精致美食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '22',
    'name' => '精致美食',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '江山市',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '江山市',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '衢州市',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '衢州市',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '柯城区',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '34',
    'name' => '柯城区',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '衢江区',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '35',
    'name' => '衢江区',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '新河沿',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '新河沿',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '斗潭',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '斗潭',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '开化县',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => '开化县',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '名品特卖',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '23',
    'name' => '名品特卖',
  ),
);
?>